#!/bin/bash

### !!! Edit after your needs
### !!! To save place use: sh -e this_script|cut -d" " -f1 |& grep -v -e "\-dbg"$ -e "\-dev"$| uniq
### !!! apt-get install $(command_from_above)
### !!! Manually copy commands for backports and use after this script is done

### Only for lightweight and GTK desktops such as XFCE. LXDE
#apt-cache search ^xfce  
#apt-cache search ^lxde

# For autoupdate 
apt-cache search ^update-notifier

## Video drivers 
apt-cache search ^xserver-xorg-video |& grep -v -e video-nvidia -e non-free

# System tools
#apt-cache search ^gksu

# Kernels
## 32Bit
##apt-cache search "linux-image" | grep -v -e pae -e amd -e nvidia
## 64Bit 
##apt-cache search "linux-image" | grep -v -e pae -e nvidia  | grep amd64
##Additional drivers
##apt-cache search ^firmware | grep ^firmware

## Printer related
apt-cache search ^cups
apt-cache search ^ghostscript
apt-cache search ^system-config-printer

#apt-cache search printer |& grep driver

###### Office related
apt-cache search ^libreoffice-l
apt-cache search ^abiword
#KDE calligra
#apt-cache search ^calligra
apt-cache search ^inkscape
# Notes
apt-cache search ^xpad
# Image edit
apt-cache search ^pinta
apt-cache search ^gimp |& grep -v gimp-ufraw

# Fonts
apt-cache search ^ttf
apt-cache search ^fonts-

# Spelling/Dictionary
#apt-cache search ^myspell
#apt-cache search ^hunspell |& grep -v -e "frami"$  -e "comprehensive" -e "modern" -e "revised" -e "myspell"
apt-cache search ^hunspell |& grep -v -e frami -e comprehensive -e revised -e modern -e classical -e myspell
apt-cache search ^aspell
apt-cache search ^ispell |& grep -v -e gut

# Viewers
apt-cache search ^calibre
apt-cache search ^xsane
apt-cache search ^evince |& grep -v gtk
apt-cache search ^calibre
apt-cache search ^ristretto
apt-cache search ^w-scan

### Web related
#apt-cache search "web browser" |& grep "web browser" |& grep lightweight
#apt-cache search "web browser" |& grep "web browser" |& grep minimal
#apt-cache search "web browser" |& grep "web browser" |& grep small
#apt-cache search ^"web browser"
apt-cache search ^midori
apt-cache search ^opera
apt-cache search ^netsurf
apt-cache search ^chromium
apt-cache search ^iceweasel-l

### widget = kde plasma
apt-cache search pulseaudio |& grep -v widget |& grep mix
apt-cache search ^pavucontrol
apt-cache search ^alsamixergui 
apt-cache search ^volumeicon-alsa

#apt-get remove flashplugin-nonfree flashplugin-nonfree-extrasound  flashplayer-mozilla

### All web browsers
##apt-cache search "web browser" |& grep -i "web browser" | grep -v -e dbg -e dev -e API -e debug -e usage -e perl -e python -e data -e php -e man -e library -e plugin -e extension -e beta -e unstable -e client -e control

#Archives/(de)compression
apt-cache search ^xarchiver
apt-cache search ^p7zip

#Media
apt-cache search ^vlc
apt-cache search ^smplayer
apt-cache search ^xine |& grep -v inetd
apt-cache search ^parole
apt-cache search ^youtube
apt-cache search ^xmms2 |& grep -v library
apt-cache search ^audacious
apt-cache search ^audacity
apt-cache search ^lxmusic
# Codecs
apt-cache search ^icedtea 
apt-cache search ^gstreamer |& grep "\-plugins"

# Burn disk
apt-cache search ^brasero
apt-cache search ^pinta
apt-cache search ^xfburn
# Chat
apt-cache search ^pidgin
apt-cache search ^empathy
apt-cache search ^xchat

apt-cache search ^skype |& grep ^skype


# Torrent
apt-cache search transmission-gtk
#apt-cache search ^transmission |& grep -v python

# FreshPlayer plugin, PPAPI-host NPAPI-plugin adapter for pepperflash
# Makes pepper flash (Adobe flash) works in firefox
#apt-cache search browser-plugin-freshplayer-pepperflash
# aptitude -t jessie-backports install browser-plugin-freshplayer-pepperflash


## NOT working  install XMMS not xmms2
## NOT working  apt-cache search ^libmikmod
### 
#sudo aptitude install fakeroot automake  build-essential
