#!/bin/bash

aptitude update
apt-get dist-upgrade

apt-get install apt-transport-https

wget -qO- https://deb.opera.com/archive.key |  apt-key add -
dpkg --add-architecture i386

wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- |  apt-key add -

#aptitude install pepperflashplugin-nonfree browser-plugin-freshplayer-pepperflash
#apt install browser-plugin-freshplayer-pepperflash
#apt-get install apt-transport-https

#Skype
aptitude install libc6:i386 libqt4-dbus:i386 libqt4-network:i386 libqt4-xml:i386 libqtcore4:i386 libqtgui4:i386 libqtwebkit4:i386 libstdc++6:i386 libx11-6:i386 libxext6:i386 libxss1:i386 libxv1:i386 libssl1.0.0:i386 libpulse0:i386 libasound2-plugins:i386
apt-get install libxcursor1:i386
###

wget -O - http://web.archive.org/web/20070117230510/http://www.skype.com/products/skype/linux/rpm-public-key.asc | apt-key add -
#apt-get install skype

wget -O - http://notesalexp.org/debian/alexp_key.asc |  apt-key add -
wget -O - http://www.tataranovich.com/tataranovich.asc |  apt-key add -
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 836CC41976FB442E
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv C697D823EB0AB654
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub |  apt-key add -

## PeerGuardian Linux
gpg --keyserver keyserver.ubuntu.com --recv-keys C0145138
gpg --export --armor C0145138 | sudo apt-key add -

#### apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EAF9B4E3C0145138


##### 

#apt-get install debian-keyring
#wget -O- -q http://mozilla.debian.net/archive.asc | apt-key add -
##wget -O- -q http://mozilla.debian.net/archive.asc | gpg --import
##gpg --check-sigs --fingerprint --keyring /usr/share/keyrings/debian-keyring.gpg 06C4AE2A
##gpg --export -a 06C4AE2A |  apt-key add -

####

wget -q -O - http://download.ag-projects.com/agp-debian-gpg.key | apt-key add -

#########
#"Debian kernel built on top of the zen kernel sources. The configuration is optimized for a practical desktop experience and features not currently maintained in Linus's mainline kernel are included." 
#apt-get update && apt-get install '^liquorix-([^-]+-)?keyring.?'

########

wget -O - http://www.bchemnet.com/suldr/suldr.gpg | apt-key add -

####

#gpg --keyserver wwwkeys.eu.pgp.net --recv 9072870B
#gpg --export --armor 9072870B |  apt-key add -
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EAF9B4E3C0145138

wget -q  -O - http://download.bitdefender.com/repos/deb/bd.key.asc| apt-key add -

#wget http://www.dotdeb.org/dotdeb.gpg
#apt-key add dotdeb.gpg
wget -q -O -  http://www.dotdeb.org/dotdeb.gpg |  apt-key add -

apt-key adv --keyserver keyserver.quickbuild.pearsoncomputing.net --recv-keys 2B8638D0

wget -q -O - http://londo.ganneff.de/apt.key | apt-key add -

#wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | apt-key add -

#problem with server connect
#gpg --keyserver wwwkeys.pgp.net --recv-keys EEF818CF
#gpg --armor --export EEF818CF |  apt-key add -

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 5BC4CFB8EEF818CF
#apt-get install scribus-archive-keyring

#apt-get update && apt-get install cathbard-keyring
apt-key adv --recv-keys --keyserver hkp://pgp.mit.edu:80 0xA5D32F012649A5A9

#QGIS
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 3FF5FFCAD71472C4
